api:
  resource: "@CustomerHuntSiteBundle/Controller/ApiController.php"
  prefix: /api
  type: annotation

replacement_dictionaries:
  resource: "@CustomerHuntSiteBundle/Controller/ReplacementDictionariesController.php"
  prefix: projects
  type: annotation

pages:
  resource: "@CustomerHuntSiteBundle/Controller/PagesController.php"
  prefix: /projects
  type: annotation

test_pages:
  resource: "@CustomerHuntSiteBundle/Controller/TestPagesController.php"
  prefix: /projects
  type: annotation

projects:
  resource: "@CustomerHuntSiteBundle/Controller/ProjectsController.php"
  prefix: /projects
  type: annotation

security:
  resource: "@CustomerHuntSiteBundle/Controller/SecurityController.php"
  prefix: /
  type: annotation

general:
  resource: "@CustomerHuntSiteBundle/Controller/GeneralController.php"
  prefix: /
  type: annotation