projects:
  resource: "@CustomerHuntSiteBundle/Controller/ProjectsController.php"
  prefix: /projects
  type: annotation

security:
  resource: "@CustomerHuntSiteBundle/Controller/SecurityController.php"
  prefix: /
  type: annotation

general:
  resource: "@CustomerHuntSiteBundle/Controller/GeneralController.php"
  prefix: /
  type: annotation