security:
  resource: "@CustomerHuntSiteBundle/Controller/SecurityController.php"
  prefix: /
  type: annotation

general:
  resource: "@CustomerHuntSiteBundle/Controller/GeneralController.php"
  prefix: /
  type: annotation