parameters:
#  empty

services:
  customer_hunt.controller_listener:
    class: CustomerHunt\SystemBundle\EventListener\ControllerListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
